model_list:
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: sk-ba116a2e478645d39fb6134bf8ffd694
      api_base: https://api.deepseek.com/v1

  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: sk-ba116a2e478645d39fb6134bf8ffd694
      api_base: https://api.deepseek.com/v1

litellm_settings:
  cache: true
  cache_params:
    type: redis
    host: localhost
    port: 6379

general_settings:
  master_key: lobster-proxy-key
