"""Risk Truth Layer reason codes (Phase-1)."""

CAPITAL_FILE_MISSING = "CAPITAL_FILE_MISSING"
CAPITAL_JSON_INVALID = "CAPITAL_JSON_INVALID"
CAPITAL_FIELDS_MISSING = "CAPITAL_FIELDS_MISSING"
CAPITAL_STALE = "CAPITAL_STALE"

STOP_INVALID = "STOP_INVALID"
STOP_TOO_TIGHT = "STOP_TOO_TIGHT"
POSITION_SIZE_INVALID = "POSITION_SIZE_INVALID"

DIRECTION_EXPOSURE_HIGH = "DIRECTION_EXPOSURE_HIGH"
PORTFOLIO_RISK_HIGH = "PORTFOLIO_RISK_HIGH"
DAY_RISK_STOP_HIT = "DAY_RISK_STOP_HIT"
